[package]
name = "aqaval"
version = "0.1.0"
authors = ["Zander Brown <ZanderBrown@users.noreply.github.com>"]
edition = "2018"

[features]
default = ["getopts", "readline"]

[dependencies]
getopts = { version = "0.2.18", optional = true }
readline = { version = "0.0.13", optional = true }
rand = "0.5.5"

[target.'cfg(target_arch = "wasm")'.dependencies.rand]
version = "0.5.5"
features = ["stdweb"]

[[bin]]
name="aqaval"
path="src/bin/aqaval.rs"
required-features = ["getopts", "readline"]
